### ISSUE TITLE
MUFFINN to non-human species?

### ISSUE THREAD

**Issue by hongenxu** [netbiolab/MUFFINN#1]
Hi, 
thanks for developing MUFFINN. Is it applicable to non-human species, for my case, chicken? What should I bear in mind when use MUFFINN for chicken genome ?

Best regards,
Hongen

**Comment by netbiolab** [comment]
Dear Hongen
Currently, MUFFINN does not provide the service with non-human genes.
The simple way to utilize MUFFINN with chicken genes would be their human orthologs.
You may obtain human orthologs of chicken genes from several databases or even find using an orthology mapping software such as Inparanoid. 
Then you can submit somatic mutation data for chicken genes as a list of human ortholog - mutation count paris.

Best

Insuk

**Comment by hongenxu** [comment]
Hi Insuk,

thanks for your help. I have a question about the second column of  MutationOccurrence_Breast.example file. Is it the count of mutations (SNVs, INDELs) in this gene? Should I sum  SNVs and Indels together? Should I only consider coding regions or include intron regions?

Best regards,
Hongen

**Comment by netbiolab** [comment]
Dear Hongen,

The second column is the number of nonsilent mutations in this gene across the individual set, therefore, I think it is the count of mutations of SNVs and INDELs all together.  You could refer the column description at http://gdac.broadinstitute.org/runs/analyses__2016_01_28/reports/cancer/BRCA/MutSigNozzleReportCV/nozzle.html > Results > Significantly Mutated Genes > ColumnDescriptions > nnon. (Although I downloaded it much earlier, so the exact number might be different) 
I hope this can help.
